const { Schema, model } = require('mongoose');

const schema = new Schema({
  id_lab: { type: String, required: true, unique: true },
  letterOne: { type: String, required: true },
  letterTwo: { type: String, required: true },
  1: { type: Number, required: true },
  2: { type: Number, required: true },
  3: { type: Number, required: true },
  4: { type: Number, required: true },
  5: { type: Number, required: true },
  6: { type: Number, required: true },
  7: { type: Number, required: true },
  8: { type: Number, required: true },
  9: { type: Number, required: true },
  10: { type: Number, required: true },
  11: { type: Number, required: true },
  12: { type: Number, required: true },
  13: { type: Number, required: true },
  14: { type: Number, required: true },
  15: { type: Number, required: true },
  16: { type: Number, required: true },
  17: { type: Number, required: true },
  18: { type: Number, required: true },
  19: { type: Number, required: true },
  20: { type: Number, required: true },
  21: { type: Number, required: true },
  22: { type: Number, required: true },
  23: { type: Number, required: true },
  24: { type: Number, required: true },
  file1: { type: String },
  file2: { type: String },
  file3: { type: String },
  file4: { type: String },
  file5: { type: String },
  file6: { type: String },
});

module.exports = model('M11model', schema);
