const { Schema, model } = require('mongoose');

const schema = new Schema({
  id_lab: { type: String, unique: true, required: true },
  withBoard: { type: Number },
  dataArray: { type: Array },
  file1: { type: String },
  file2: { type: String },
  file3: { type: String },
  file4: { type: String },
  file5: { type: String },
  file6: { type: String },
  output1: { type: String },
  file_1: { type: String },
  output2: { type: String },
  file_2: { type: String },
  output3: { type: String },
  file_3: { type: String },
  output4: { type: String },
  file_4: { type: String },
});

module.exports = model('M12model', schema);

// 1: { type: Number },
// 2: { type: Number },
// 3: { type: Number },
// 4: { type: Number },
// 5: { type: Number },
// 6: { type: Number },
// 7: { type: Number },
// 8: { type: Number },
// 9: { type: Number },
// 10: { type: Number },
// 11: { type: Number },
// 12: { type: Number },
// 13: { type: Number },
// 14: { type: Number },
// 15: { type: Number },
// 16: { type: Number },
// 17: { type: Number },
// 18: { type: Number },
// 19: { type: Number },
// 20: { type: Number },
// 21: { type: Number },
// 22: { type: Number },
// 23: { type: Number },
// 24: { type: Number },
// 25: { type: Number },
// 26: { type: Number },
// 27: { type: Number },
// 28: { type: Number },
// 29: { type: Number },
// 30: { type: Number },
// 31: { type: Number },
// 32: { type: Number },
// 33: { type: Number },
// 34: { type: Number },
// 35: { type: Number },
// 36: { type: Number },
// 37: { type: Number },
// 38: { type: Number },
// 39: { type: Number },
// 40: { type: Number },
// 41: { type: Number },
// 42: { type: Number },
// 43: { type: Number },
// 44: { type: Number },
// 45: { type: Number },
// 46: { type: Number },
// 47: { type: Number },
// 48: { type: Number },
// 49: { type: Number },
// 50: { type: Number },
// 51: { type: Number },
// 52: { type: Number },
// 53: { type: Number },
// 54: { type: Number },
// 55: { type: Number },
// 56: { type: Number },
// 57: { type: Number },
// 58: { type: Number },
// 59: { type: Number },
// 60: { type: Number },
// 61: { type: Number },
// 62: { type: Number },
// 63: { type: Number },
// 64: { type: Number },
// 65: { type: Number },
// 66: { type: Number },
// 67: { type: Number },
// 68: { type: Number },
// 69: { type: Number },
// 70: { type: Number },
// 71: { type: Number },
// 72: { type: Number },
// 73: { type: Number },
// 74: { type: Number },
// 75: { type: Number },
// 76: { type: Number },
// 77: { type: Number },
// 78: { type: Number },
// 79: { type: Number },
// 80: { type: Number },
// 81: { type: Number },
// 82: { type: Number },
// 83: { type: Number },
// 84: { type: Number },
// 85: { type: Number },
// 86: { type: Number },
// 87: { type: Number },
// 88: { type: Number },
// 89: { type: Number },
// 90: { type: Number },
// 91: { type: Number },
// 92: { type: Number },
// 93: { type: Number },
// 94: { type: Number },
// 95: { type: Number },
// 96: { type: Number },
// 97: { type: Number },
// 98: { type: Number },
// 99: { type: Number },
// 100: { type: Number },
// 101: { type: Number },
// 102: { type: Number },
// 103: { type: Number },
// 104: { type: Number },
// 105: { type: Number },
// 106: { type: Number },
// 107: { type: Number },
// 108: { type: Number },
// 109: { type: Number },
// 110: { type: Number },
// 111: { type: Number },
// 112: { type: Number },
